### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by M00NJ** [cosmic-utils/tasks#34]
I've been using tasks for a while now and enjoy it a lot. There are some changes to the UI I'd like to suggest though, so I created a mockup. I've looked at other task managers like Errands and Planify and also the Cosmic apps for reference. 

![Mockup](https://github.com/user-attachments/assets/951bfb65-02c6-48e5-b1f0-e6144996b1e7)

My main suggestion is to remove most of the high emphasis icon buttons, since they make the UI look quite busy. The default Cosmic apps have a minimalistic approach and don't use them. So I'd drop them where they are not necessary, like the button for adding new tasks. You need to use the keyboard to write the task name, so you'll probably just press enter instead. Also the icon looks more like a send button in a messenger app to me. The same goes for the edit button. You can edit the task name by clicking on it. This is more intuitive, so I'd drop that button as well. I would also replace the export button, with a button to move all completed tasks to the trash. Errands has this feature and it's quite useful. I'd make the export functionality accessible via the files menu in the window header instead. I don't think people are exporting their list three times a day, so that space could be utilized better. With a new button to remove completed tasks, the trash button behind every task could be dropped as well. Again making the UI cleaner and avoiding component duplication. So the only button I'd keep there is for opening the context drawer. I'd also split tasks into separate cards and show a expand / collapse icon on hover if a task has sub-tasks, like Errands. Clicking anywhere on the task (except the name) could expand or collapse it, so the target area is bigger than a button. Showing the number of uncompleted task in a list and the progress for each task would also the helpful. The context drawer is great already, I'd just apply the same things as above to the sub-task section too. Lastly, context menus could be used to expose more actions, without cluttering the UI. 

Maybe some of these ideas are useful to you. Thank you for this great application :)

**Comment by edfloreshz** [comment]
I've been wanting to improve the UI but had no idea how, now I know. 

I'll work on this for the next release. 🎉 

This is great feedback, thanks for taking the time with the mock up and the issue 👍🏼  

## To-do's:

- [x] Remove high-emphasis icon buttons.
- [x] Use context menus for tasks.
- [x] Use separate cards for tasks with expand/collapse functionality.
- [x] Show task progress and number of uncompleted sub-tasks.
- [ ] Show number of tasks in a list.
- [x] Move export functionality to navigation menu.
- [ ] Add button to move all completed tasks to the trash.

**Comment by edfloreshz** [comment]
There's currently an issue with context menus, which is preventing me from implementing the suggested behavior.

**Comment by edfloreshz** [comment]
Managed to implement some things already:

![image](https://github.com/user-attachments/assets/41177661-26bd-4370-9bdf-53a2ac7debbb)
Context menu

![image](https://github.com/user-attachments/assets/5b84eae1-ba82-46f1-8032-bb4952f58f4a)
Details

![image](https://github.com/user-attachments/assets/3d993dc4-2b2b-4bdf-8a64-70fd7dcb22fc)
Export

**Comment by M00NJ** [comment]
Wow, that was fast! The app looks very polished now :)

**Comment by edfloreshz** [comment]
I need to sleep now, I've been coding straight for 8-9 hours 😴

**Comment by M00NJ** [comment]
Please don't over-work yourself. Burnout is no fun. There are no deadlines is the foss world... :relieved:

**Comment by edfloreshz** [comment]
I got a little carried away, working on this is fun for me!

**Comment by edfloreshz** [comment]
I haven't had a chance to take a look at that, but it is most likely related to libcosmic or flatpak.

**Comment by herrdiener** [comment]
Could this be merged, even if it's partial progress? This would be a significant improvement to both user experience and usability.

**Comment by edfloreshz** [comment]
I worked on this a while back but I faced some issues, I'll try to tackle this again and see how it goes.

**Comment by edfloreshz** [comment]
@M00NJ I'm getting quite close to completing this request

![Image](https://github.com/user-attachments/assets/e834a197-5db4-4546-a83e-52bdf74f1543)

![Image](https://github.com/user-attachments/assets/5a0f4762-7e06-49b8-961c-f110032bb7c5)

**Comment by edfloreshz** [comment]
@herrdiener I have merged my progress so far, feel free to review it and let me know your thoughts 👍🏼

**Comment by edfloreshz** [comment]
Thanks! I'll include it once I work on that feature.

**Comment by herrdiener** [comment]
Brilliant work, thank you! The interface now looks classy and keeps the attention where it needs to be.

(Also during the last two hours, you've been fixing regressions faster than I was able to report them - mad respect.)

I've only noticed a tiny usability peeve, which, since this is merged to master, I've opened a [separate issue](https://github.com/cosmic-utils/tasks/issues/66) for.
